services:
  bookmarks:
    image: hacdias/webdav
    container_name: bookmarks
    restart: unless-stopped
    volumes:
      - ./config.yml:/config.yml:ro
      - ${DATA_ROOT:?}/documents/bookmarks:/data
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
