name: intrahub

include:
  - services/mediavault/compose.yaml
  - services/jellyfin/compose.yaml
  - services/bookorbit/compose.yaml
  - services/samba/compose.yaml
  - services/bookmarks/compose.yaml
  - services/litellm/compose.yaml
  - services/mastra/compose.yaml
  - services/hermes-agent/compose.yaml
  - services/netdata/compose.yaml
