services:
  samba:
    image: dockurr/samba
    container_name: samba
    restart: unless-stopped
    environment:
      TZ: ${TZ:?}
      SAMBA_USER: ${SAMBA_USER:?}
      SAMBA_PASSWORD: ${SAMBA_PASSWORD:?}
    ports:
      - "445:445"
      - "139:139"
    volumes:
      - ${DATA_ROOT:?}/media/video:/shares/video
      - ${DATA_ROOT:?}/media/photo:/shares/photo
      - ${DATA_ROOT:?}/documents/pdf:/shares/pdf
      - ${DATA_ROOT:?}/documents/manga:/shares/manga
      - ${DATA_ROOT:?}/documents/archives:/shares/archives
      - ${DATA_ROOT:?}/documents/ocr:/shares/ocr
      - ${DATA_ROOT:?}/documents/vault:/shares/vault
    networks:
      - files-net

networks:
  files-net:
    driver: bridge
